[package]
name = "recaptcha"
description = "recaptcha response verification"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]
license = "MIT"
keywords = ["recaptcha", "captcha"]
repository = "https://github.com/panicbit/recaptcha-rs"

[dependencies]
reqwest = "0.8.8"
serde_derive = "1.0.76"
serde = "1.0.76"
failure = "0.1.2"

[dev-dependencies]
serde_json = "1.0.26"
